/** @type {import('cspell').CSpellUserSettings} */
module.exports = {
  version: '0.2',
  language: 'es-ES',
  allowCompoundWords: true,
  ignorePaths: [
    'node_modules',
    'dist',
    '.git',
    '.husky',
    'supabase/.temp',
    'package-lock.json',
    'public',
    '**/*.png',
    '**/*.jpg',
    '**/*.jpeg',
    '**/*.svg',
  ],
  files: ['**/*.{md,mdx,ts,tsx,json}'],
  dictionaries: ['es-es', 'softwareTerms', 'companies'],
  dictionaryDefinitions: [
    {
      name: 'es-es',
      path: '@cspell/dict-es-es/es-es.dict',
      description: 'Diccionario español (España)',
    },
    {
      name: 'softwareTerms',
      path: '@cspell/dict-software-terms/software-terms.dict',
      description: 'Términos técnicos',
    },
    {
      name: 'companies',
      path: '@cspell/dict-companies/companies.dict',
      description: 'Nombres de empresas',
    },
  ],
  words: [
    'Traductor',
    'Burocratico',
    'Supabase',
    'Tailwind',
    'Vite',
    'TypeScript',
    'TB',
    'Turnstile',
    'Recaptcha',
    'Postgres',
    'LLM',
    'LLMs',
    'frontend',
    'backend',
    'webhooks',
    'Hostinger',
    'CSP',
    'RLS',
    'CTA',
    'Auth',
    'Edge',
    'Hotkey',
  ],
};
